// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.moyada.serializer.data.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.moyada.serializer.data.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>sfixed32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>bool gender = 4;</code>
     */
    boolean getGender();

    /**
     * <code>double scope = 5;</code>
     */
    double getScope();

    /**
     * <code>repeated string identifies = 6;</code>
     */
    java.util.List<java.lang.String>
        getIdentifiesList();
    /**
     * <code>repeated string identifies = 6;</code>
     */
    int getIdentifiesCount();
    /**
     * <code>repeated string identifies = 6;</code>
     */
    java.lang.String getIdentifies(int index);
    /**
     * <code>repeated string identifies = 6;</code>
     */
    com.google.protobuf.ByteString
        getIdentifiesBytes(int index);

    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */
    int getInfoCount();
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */
    boolean containsInfo(
        java.lang.String key);
    /**
     * Use {@link #getInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getInfo();
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getInfoMap();
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    java.lang.String getInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    java.lang.String getInfoOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code io.moyada.serializer.data.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.moyada.serializer.data.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      identifies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 29: {

              age_ = input.readSFixed32();
              break;
            }
            case 32: {

              gender_ = input.readBool();
              break;
            }
            case 41: {

              scope_ = input.readDouble();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                identifies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              identifies_.add(s);
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                info_ = com.google.protobuf.MapField.newMapField(
                    InfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              info__ = input.readMessage(
                  InfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              info_.getMutableMap().put(
                  info__.getKey(), info__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          identifies_ = identifies_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.moyada.serializer.data.proto.UserProto.User.class, io.moyada.serializer.data.proto.UserProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>sfixed32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private boolean gender_;
    /**
     * <code>bool gender = 4;</code>
     */
    public boolean getGender() {
      return gender_;
    }

    public static final int SCOPE_FIELD_NUMBER = 5;
    private double scope_;
    /**
     * <code>double scope = 5;</code>
     */
    public double getScope() {
      return scope_;
    }

    public static final int IDENTIFIES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList identifies_;
    /**
     * <code>repeated string identifies = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIdentifiesList() {
      return identifies_;
    }
    /**
     * <code>repeated string identifies = 6;</code>
     */
    public int getIdentifiesCount() {
      return identifies_.size();
    }
    /**
     * <code>repeated string identifies = 6;</code>
     */
    public java.lang.String getIdentifies(int index) {
      return identifies_.get(index);
    }
    /**
     * <code>repeated string identifies = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifiesBytes(int index) {
      return identifies_.getByteString(index);
    }

    public static final int INFO_FIELD_NUMBER = 7;
    private static final class InfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_InfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> info_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInfo() {
      if (info_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InfoDefaultEntryHolder.defaultEntry);
      }
      return info_;
    }

    public int getInfoCount() {
      return internalGetInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    public boolean containsInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInfo() {
      return getInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getInfoMap() {
      return internalGetInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    public java.lang.String getInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; info = 7;</code>
     */

    public java.lang.String getInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeSFixed32(3, age_);
      }
      if (gender_ != false) {
        output.writeBool(4, gender_);
      }
      if (scope_ != 0D) {
        output.writeDouble(5, scope_);
      }
      for (int i = 0; i < identifies_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, identifies_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetInfo(),
          InfoDefaultEntryHolder.defaultEntry,
          7);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(3, age_);
      }
      if (gender_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, gender_);
      }
      if (scope_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, scope_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < identifies_.size(); i++) {
          dataSize += computeStringSizeNoTag(identifies_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdentifiesList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        info__ = InfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, info__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.moyada.serializer.data.proto.UserProto.User)) {
        return super.equals(obj);
      }
      io.moyada.serializer.data.proto.UserProto.User other = (io.moyada.serializer.data.proto.UserProto.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getGender()
          != other.getGender()) return false;
      if (java.lang.Double.doubleToLongBits(getScope())
          != java.lang.Double.doubleToLongBits(
              other.getScope())) return false;
      if (!getIdentifiesList()
          .equals(other.getIdentifiesList())) return false;
      if (!internalGetInfo().equals(
          other.internalGetInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGender());
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getScope()));
      if (getIdentifiesCount() > 0) {
        hash = (37 * hash) + IDENTIFIES_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifiesList().hashCode();
      }
      if (!internalGetInfo().getMap().isEmpty()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.moyada.serializer.data.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.moyada.serializer.data.proto.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.moyada.serializer.data.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.moyada.serializer.data.proto.User)
        io.moyada.serializer.data.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.moyada.serializer.data.proto.UserProto.User.class, io.moyada.serializer.data.proto.UserProto.User.Builder.class);
      }

      // Construct using io.moyada.serializer.data.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        age_ = 0;

        gender_ = false;

        scope_ = 0D;

        identifies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableInfo().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.moyada.serializer.data.proto.UserProto.internal_static_io_moyada_serializer_data_proto_User_descriptor;
      }

      @java.lang.Override
      public io.moyada.serializer.data.proto.UserProto.User getDefaultInstanceForType() {
        return io.moyada.serializer.data.proto.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public io.moyada.serializer.data.proto.UserProto.User build() {
        io.moyada.serializer.data.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.moyada.serializer.data.proto.UserProto.User buildPartial() {
        io.moyada.serializer.data.proto.UserProto.User result = new io.moyada.serializer.data.proto.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.gender_ = gender_;
        result.scope_ = scope_;
        if (((bitField0_ & 0x00000020) != 0)) {
          identifies_ = identifies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.identifies_ = identifies_;
        result.info_ = internalGetInfo();
        result.info_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.moyada.serializer.data.proto.UserProto.User) {
          return mergeFrom((io.moyada.serializer.data.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.moyada.serializer.data.proto.UserProto.User other) {
        if (other == io.moyada.serializer.data.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getGender() != false) {
          setGender(other.getGender());
        }
        if (other.getScope() != 0D) {
          setScope(other.getScope());
        }
        if (!other.identifies_.isEmpty()) {
          if (identifies_.isEmpty()) {
            identifies_ = other.identifies_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureIdentifiesIsMutable();
            identifies_.addAll(other.identifies_);
          }
          onChanged();
        }
        internalGetMutableInfo().mergeFrom(
            other.internalGetInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.moyada.serializer.data.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.moyada.serializer.data.proto.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>sfixed32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>sfixed32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private boolean gender_ ;
      /**
       * <code>bool gender = 4;</code>
       */
      public boolean getGender() {
        return gender_;
      }
      /**
       * <code>bool gender = 4;</code>
       */
      public Builder setGender(boolean value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool gender = 4;</code>
       */
      public Builder clearGender() {
        
        gender_ = false;
        onChanged();
        return this;
      }

      private double scope_ ;
      /**
       * <code>double scope = 5;</code>
       */
      public double getScope() {
        return scope_;
      }
      /**
       * <code>double scope = 5;</code>
       */
      public Builder setScope(double value) {
        
        scope_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double scope = 5;</code>
       */
      public Builder clearScope() {
        
        scope_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList identifies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdentifiesIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          identifies_ = new com.google.protobuf.LazyStringArrayList(identifies_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIdentifiesList() {
        return identifies_.getUnmodifiableView();
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public int getIdentifiesCount() {
        return identifies_.size();
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public java.lang.String getIdentifies(int index) {
        return identifies_.get(index);
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifiesBytes(int index) {
        return identifies_.getByteString(index);
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public Builder setIdentifies(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentifiesIsMutable();
        identifies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public Builder addIdentifies(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentifiesIsMutable();
        identifies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public Builder addAllIdentifies(
          java.lang.Iterable<java.lang.String> values) {
        ensureIdentifiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, identifies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public Builder clearIdentifies() {
        identifies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string identifies = 6;</code>
       */
      public Builder addIdentifiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdentifiesIsMutable();
        identifies_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> info_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetInfo() {
        if (info_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              InfoDefaultEntryHolder.defaultEntry);
        }
        return info_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableInfo() {
        onChanged();;
        if (info_ == null) {
          info_ = com.google.protobuf.MapField.newMapField(
              InfoDefaultEntryHolder.defaultEntry);
        }
        if (!info_.isMutable()) {
          info_ = info_.copy();
        }
        return info_;
      }

      public int getInfoCount() {
        return internalGetInfo().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public boolean containsInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getInfo() {
        return getInfoMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getInfoMap() {
        return internalGetInfo().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public java.lang.String getInfoOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public java.lang.String getInfoOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearInfo() {
        internalGetMutableInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public Builder removeInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableInfo() {
        return internalGetMutableInfo().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */
      public Builder putInfo(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; info = 7;</code>
       */

      public Builder putAllInfo(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.moyada.serializer.data.proto.User)
    }

    // @@protoc_insertion_point(class_scope:io.moyada.serializer.data.proto.User)
    private static final io.moyada.serializer.data.proto.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.moyada.serializer.data.proto.UserProto.User();
    }

    public static io.moyada.serializer.data.proto.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.moyada.serializer.data.proto.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_moyada_serializer_data_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_moyada_serializer_data_proto_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_moyada_serializer_data_proto_User_InfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_moyada_serializer_data_proto_User_InfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\037io.moyada.serializer.data." +
      "proto\"\314\001\n\004User\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t" +
      "\022\013\n\003age\030\003 \001(\017\022\016\n\006gender\030\004 \001(\010\022\r\n\005scope\030\005" +
      " \001(\001\022\022\n\nidentifies\030\006 \003(\t\022=\n\004info\030\007 \003(\0132/" +
      ".io.moyada.serializer.data.proto.User.In" +
      "foEntry\032+\n\tInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001B\013B\tUserProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_moyada_serializer_data_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_moyada_serializer_data_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_moyada_serializer_data_proto_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Gender", "Scope", "Identifies", "Info", });
    internal_static_io_moyada_serializer_data_proto_User_InfoEntry_descriptor =
      internal_static_io_moyada_serializer_data_proto_User_descriptor.getNestedTypes().get(0);
    internal_static_io_moyada_serializer_data_proto_User_InfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_moyada_serializer_data_proto_User_InfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
